apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
  labels:
    app: nextjs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs-deployment
  template:
    metadata:
      labels:
        app: nextjs-deployment
    spec:
      containers:
      - name: nextjs-deploy
        image: registry.digitalocean.com/k8s-demo/nextjs:latest
        ports:
        - containerPort: 3000
        - containerPort: 3001
        imagePullPolicy: Always

