apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
  labels:
    app: nextjs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs-deployment
  template:
    metadata:
      labels:
        app: nextjs-deployment
    spec:
      containers:
      - name: admin-deploy
        image: registry.digitalocean.com/showcase-registry/admin
        ports:
        - containerPort: 3000
        imagePullPolicy: Always

      - name: client-deploy
        image: registry.digitalocean.com/showcase-registry/client
        ports:
        - containerPort: 3002
        imagePullPolicy: Always
