version: '2'

services:
  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    image: client
    ports:
      - '3002'
    networks:
      - app_network

  admin:
    build:
      context: .
      dockerfile: admin.Dockerfile
    image: admin
    ports:
      - '3000'
    networks:
      - app_network

networks:
  app_network:
    external: true
