
on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'Dockerfile'
      - '.github/workflows/**' 
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout master
      uses: actions/checkout@main
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: auth
      run: doctl auth init --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: create network
      run: docker network create "app_network"
    - name: Build images
      run: docker compose up -d
    - name: Tag client
      run: docker tag client registry.digitalocean.com/showcase-registry/client:v1.0.0
    - name: Tag admin
      run: docker tag admin registry.digitalocean.com/showcase-registry/admin:v1.0.0
    - name: Push client
      run: docker push registry.digitalocean.com/showcase-registry/client:v1.0.0
    - name: Push admin
      run: docker push registry.digitalocean.com/showcase-registry/admin:v1.0.0
    - name: Doctl login
      run: doctl registry login
    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-dev
    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -f ${GITHUB_WORKSPACE}/deployment.yml

