
on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'Dockerfile'
      - '.github/workflows/**' 
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout master
      uses: actions/checkout@main
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Install CLI
      run: sudo apt-get update \
           sudo add-apt-repository ppa:cncf-buildpacks/pack-cli \
           sudo apt-get update \
           sudo apt-get install pack-cli
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200
    - name: Giver permission
      run: chmod +x ./release-scripts/cnb-docker-images.sh
    - name: Build and push container image
      run: bash ${GITHUB_WORKSPACE}/release-scripts/cnb-docker-images.sh  
    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}
    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -f $GITHUB_WORKSPACE/config/deployment.yml
