
on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'Dockerfile'
      - '.github/workflows/**' 
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout master
      uses: actions/checkout@main
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Build images
      run: docker compose up
    - name: Tag client
      run: docker tag client registry.digitalocean.com/showcase-registry/client:v.1.0.0
    - name: Tag admin
      run: docker tag admin registry.digitalocean.com/showcase-registry/admin:v.1.0.0
    - name: Push client
      run: docker push registry.digitalocean.com/showcase-registry/client:v1.0.0
    - name: Push admin
      run: docker push registry.digitalocean.com/showcase-registry/admin:v1.0.0
    - name: Deploy Service
      run: kubectl apply -f $GITHUB_WORKSPACE/config/service.yml
    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -f $GITHUB_WORKSPACE/config/deployment.yml
